### ISSUE TITLE
As a buildpack author, I must specify run images in my builder.toml

### ISSUE THREAD

**Issue by sclevine** [buildpacks/roadmap#47]
**Acceptance Criteria**
**When** I run `pack create-builder my-builder -b ./builder.toml`
**Then** `builder.toml` must contain the following mandatory fields for the command to succeed:
```toml
[stack]
id = ""
build-image = ""
run-image = ""
```
**And** `builder.toml` may contain the following optional field:
```toml
[stack]
run-image-mirrors = [""]
```
**Such That** During `pack build`, run image mirrors are considered in the following order:
1. Locally-defined **mirrors** in `[[run-images]]` in config.toml (see #38)
2. **Mirrors** specified in the builder metadata
3. The canonical run image

**And** The `--stack` argument to `pack create-builder` is no longer accepted

**Notes**
- Ignore the `[[stacks]]` list in config.toml.
